# Generated by Django 2.2.2 on 2019-06-16 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_auto_20190616_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestscoresheet',
            old_name='mouthfee',
            new_name='mouthfeel',
        ),
    ]
