# Generated by Django 2.2.2 on 2019-06-16 23:21
# Populates the descriptor table

from django.db import migrations


def populate_descriptor(apps, schema_editor):
    descriptor_data = [
        {
    		'name': 'Acetaldehyde',
    		'description': 'Green apple-like aroma and flavor. Appearance (as appropriate for style)',
        },
        {
    		'name': 'Alcoholic',
    		'description': 'The aroma, flavor, and warming effect of ethanol and higher alcohols. Sometimes described as hot.',
        },
        {
    		'name': 'Astringent',
    		'description': 'Puckering, lingering harshness and/or dryness in the finish/aftertaste; harsh graininess; huskiness.',
        },
        {
    		'name': 'Diacetyl',
    		'description': 'Artificial butter, butterscotch, or toffee aroma and flavor. Sometimes perceived as a slickness on the tongue.',
        },
        {
    		'name': 'DMS',
    		'description': 'At low levels a sweet, cooked or canned corn-like aroma and flavor.',
        },
        {
    		'name': 'Estery',
    		'description': 'Aroma and/or flavor of any ester (fruits, fruit flavorings, or roses).',
        },
        {
    		'name': 'Grassy',
    		'description': 'Aroma/flavor of fresh-cut grass or green leaves.',
        },
        {
    		'name': 'Light-Struck',
    		'description': 'Similar to the aroma of a skunk. Mouthfeel (as appropriate for style).',
        },
        {
    		'name': 'Metallic',
    		'description': 'Tinny, coiny, copper, iron, or blood-like flavor.',
        },
        {
    		'name': 'Oxidized',
    		'description': 'Any one or combination of stale, winy/vinous, cardboard, papery, or sherry-like aromas and flavors. ',
        },
        {
    		'name': 'Phenolic',
    		'description': 'Spicy (clove, pepper), smoky, plastic, plastic adhesive strip, and/or medicinal (chlorophenolic). Overall Impression',
        },
        {
    		'name': 'Musty',
    		'description': 'Stale, musty, or moldy aromas/flavors.',
        },
        {
    		'name': 'Solvent',
    		'description': 'Aromas and flavors of higher alcohols (fusel alcohols). Similar to acetone or lacquer thinner aromas.',
        },
        {
    		'name': 'Sour-acidic',
    		'description': 'Tartness in aroma and flavor. Can be sharp and clean (lactic acid), or vinegar-like (acetic acid).',
        },
        {
    		'name': 'Sulfur',
    		'description': 'The aroma of rotten eggs or burning matches.',
        },
        {
    		'name': 'Vegetal',
    		'description': 'Cooked, canned, or rotten vegetable aroma and flavor (cabbage, onion, celery, asparagus, etc.)',
        },
        {
    		'name': 'Yeasty',
    		'description': 'A bready, sulfury or yeast-like aroma or flavor.',
        },
    ]
    DescriptorDefinition = apps.get_model('competitions', 'DescriptorDefinition')
    for d in descriptor_data:
        dd = DescriptorDefinition(name=d['name'], description=d['description'])
        dd.save()

class Migration(migrations.Migration):
    dependencies = [
        ('competitions', '0003_auto_20190616_2318'),
    ]

    operations = [
        migrations.RunPython(populate_descriptor),
    ]
