# Generated by Django 2.2.2 on 2019-06-17 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_contestcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='contesttable',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='competitions.ContestCategory'),
            preserve_default=False,
        ),
    ]
