# Generated by Django 2.2.2 on 2019-06-29 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_contestscoresheet_total_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestscoresheet',
            old_name='intangilble',
            new_name='intangible',
        ),
    ]
