# Generated by Django 2.2.2 on 2019-06-28 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_contestscoresheet_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contesttable',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='competitions.ContestCategory'),
        ),
    ]
