# Generated by Django 2.2.2 on 2019-07-02 01:37

from django.db import migrations

def populate_descriptor(apps, schema_editor):
    category_data = [
        {
            'name': '01 - Standard American Beer'
        },
        {
            'name': '02 - International Lager'
        },
        {
            'name': '03 - Czech Lager'
        },
        {
            'name': '04 - Pale Malty European Lager'
        },
        {
            'name': '05 - Pale Bitter European beer'
        },
        {
            'name': '06 - Amber Malty European Lager'
        },
        {
            'name': '07 - Amber Bitter European Beer'
        },
        {
            'name': '08 - Dark European Lager'
        },
        {
            'name': '09 - Strong European Beer'
        },
        {
            'name': '10 - German Wheat Beer'
        },
        {
            'name': '11 - British Bitter'
        },
        {
            'name': '12 - Pale Commonwealth Beer'
        },
        {
            'name': '13 - Brown British Beer'
        },
        {
            'name': '14 - Scottish Ale'
        },
        {
            'name': '15 - Irish Beer'
        },
        {
            'name': '16 - Dark British Beer'
        },
        {
            'name': '17 - Strong British Ale'
        },
        {
            'name': '18 - Pale American Ale'
        },
        {
            'name': '19 - Amber and Brown American Beer'
        },
        {
            'name': '20 - American Porter and Stout'
        },
        {
            'name': '21 - IPA'
        },
        {
            'name': '22 - Strong American Ale'
        },
        {
            'name': '23 - European Sour Ale'
        },
        {
            'name': '24 - Belgian Ale'
        },
        {
            'name': '25 - Strong Belgian Ale'
        },
        {
            'name': '26 - Trappist Ale'
        },
        {
            'name': '27 - Historical Beer'
        },
        {
            'name': '28 - American Wild Ale'
        },
        {
            'name': '29 - Fruit Beer'
        },
        {
            'name': '30 - Spiced Beer'
        },
        {
            'name': '31 - Alternative Fermentables Beer'
        },
        {
            'name': '32 - Smoked Beer'
        },
        {
            'name': '33 - Wood Beer'
        },
        {
            'name': '34 - Specialty Beer'
        },
    ]
    BJCPCategories = apps.get_model('competitions', 'BJCPcategory')
    for d in category_data:
        cc = BJCPCategories(name=d['name'])
        cc.save()



class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_auto_20190629_2020'),
    ]

    operations = [
        migrations.RunPython(populate_descriptor),
    ]
