# Generated by Django 2.2.2 on 2019-07-02 02:01

from django.db import migrations

def populate_style(apps, schema_editor):
    style_data = [
        {
            'name': '01A - American Light Lager',
            'category': '01 - Standard American Beer',
        },
        {
            'name': '01B - American Lager',
            'category': '01 - Standard American Beer',
        },
        {
            'name': '01C - Cream Ale',
            'category': '01 - Standard American Beer',
        },
        {
            'name': '01D - American Wheat Beer',
            'category': '01 - Standard American Beer',
        },
        {
            'name': '02A - International Pale Lager',
            'category': '02 - International Lager',
        },
        {
            'name': '02B - International Amber Lager',
            'category': '02 - International Lager',
        },
        {
            'name': '02C - International Dark Lager',
            'category': '02 - International Lager',
        },
        {
            'name': '03A - Czech Pale Lager',
            'category': '03 - Czech Lager',
        },
        {
            'name': '03B - Czech Premium Pale Lager',
            'category': '03 - Czech Lager',
        },
        {
            'name': '03C - Czech Amber Lager',
            'category': '03 - Czech Lager',
        },
        {
            'name': '03D - Czech Dark Lager',
            'category': '03 - Czech Lager',
        },
        {
            'name': '04A - Munich Helles',
            'category': '04 - Pale Malty European Lager',
        },
        {
            'name': '04B - Festbier',
            'category': '04 - Pale Malty European Lager',
        },
        {
            'name': '04C - Helles Bock',
            'category': '04 - Pale Malty European Lager',
        },
        {
            'name': '05A - German Leichtbier',
            'category': '05 - Pale Bitter European beer',
        },
        {
            'name': '05B - Kölsch',
            'category': '05 - Pale Bitter European beer',
        },
        {
            'name': '05C - German Helles Exportbier',
            'category': '05 - Pale Bitter European beer',
        },
        {
            'name': '05D - German Pils',
            'category': '05 - Pale Bitter European beer',
        },
        {
            'name': '06A - Märzen',
            'category': '06 - Amber Malty European Lager',
        },
        {
            'name': '06B - Rauchbier',
            'category': '06 - Amber Malty European Lager',
        },
        {
            'name': '06C - Dunkles Bock',
            'category': '06 - Amber Malty European Lager',
        },
        {
            'name': '07A - Vienna Lager',
            'category': '07 - Amber Bitter European Beer',
        },
        {
            'name': '07B - Altbier',
            'category': '07 - Amber Bitter European Beer',
        },
        {
            'name': '07C - Pale Kellerbier',
            'category': '07 - Amber Bitter European Beer',
        },
        {
            'name': '07C - Amber Kellerbier',
            'category': '07 - Amber Bitter European Beer',
        },
        {
            'name': '08A - Munich Dunkel',
            'category': '08 - Dark European Lager',
        },
        {
            'name': '08B - Schwarzbier',
            'category': '08 - Dark European Lager',
        },
        {
            'name': '09A - Doppelbock',
            'category': '09 - Strong European Beer',
        },
        {
            'name': '09B - Eisbock',
            'category': '09 - Strong European Beer',
        },
        {
            'name': '09C - Baltic Porter',
            'category': '09 - Strong European Beer',
        },
        {
            'name': '10A - Weissbier',
            'category': '10 - German Wheat Beer',
        },
        {
            'name': '10B - Dunkles Weissbier',
            'category': '10 - German Wheat Beer',
        },
        {
            'name': '10C - Weizenbock',
            'category': '10 - German Wheat Beer',
        },
        {
            'name': '11A - Ordinary Bitter',
            'category': '11 - British Bitter',
        },
        {
            'name': '11B - Best Bitter',
            'category': '11 - British Bitter',
        },
        {
            'name': '11C - Strong Bitter',
            'category': '11 - British Bitter',
        },
        {
            'name': '12A - British Golden Ale',
            'category': '12 - Pale Commonwealth Beer',
        },
        {
            'name': '12B - Australian Sparkling Ale',
            'category': '12 - Pale Commonwealth Beer',
        },
        {
            'name': '12C - English IPA',
            'category': '12 - Pale Commonwealth Beer',
        },
        {
            'name': '13A - Dark Mild',
            'category': '13 - Brown British Beer',
        },
        {
            'name': '13B - British Brown Ale',
            'category': '13 - Brown British Beer',
        },
        {
            'name': '13C - English Porter',
            'category': '13 - Brown British Beer',
        },
        {
            'name': '14A - Scottish Light',
            'category': '14 - Scottish Ale',
        },
        {
            'name': '14B - Scottish Heavy',
            'category': '14 - Scottish Ale',
        },
        {
            'name': '14C - Scottish Export',
            'category': '14 - Scottish Ale',
        },
        {
            'name': '15A - Irish Red Ale',
            'category': '15 - Irish Beer',
        },
        {
            'name': '15B - Irish Stout',
            'category': '15 - Irish Beer',
        },
        {
            'name': '15C - Irish Extra Stout',
            'category': '15 - Irish Beer',
        },
        {
            'name': '16A - Sweet Stout',
            'category': '16 - Dark British Beer',
        },
        {
            'name': '16B - Oatmeal Stout',
            'category': '16 - Dark British Beer',
        },
        {
            'name': '16C - Tropical Stout',
            'category': '16 - Dark British Beer',
        },
        {
            'name': '16D - Foreign Extra Stout',
            'category': '16 - Dark British Beer',
        },
        {
            'name': '17A - British Strong Ale',
            'category': '17 - Strong British Ale',
        },
        {
            'name': '17B - Old Ale',
            'category': '17 - Strong British Ale',
        },
        {
            'name': '17C - Wee Heavy',
            'category': '17 - Strong British Ale',
        },
        {
            'name': '17D - English Barleywine',
            'category': '17 - Strong British Ale',
        },
        {
            'name': '18A - Blonde Ale',
            'category': '18 - Pale American Ale',
        },
        {
            'name': '18B - American Pale Ale',
            'category': '18 - Pale American Ale',
        },
        {
            'name': '19A - American Amber Ale',
            'category': '19 - Amber and Brown American Beer',
        },
        {
            'name': '19B - California Common',
            'category': '19 - Amber and Brown American Beer',
        },
        {
            'name': '19C - American Brown Ale',
            'category': '19 - Amber and Brown American Beer',
        },
        {
            'name': '20A - American Porter',
            'category': '20 - American Porter and Stout',
        },
        {
            'name': '20B - American Stout',
            'category': '20 - American Porter and Stout',
        },
        {
            'name': '20C - Imperial Stout',
            'category': '20 - American Porter and Stout',
        },
        {
            'name': '21A - American IPA',
            'category': '21 - IPA',
        },
        {
            'name': '21B - Specialty IPA - Belgian IPA',
            'category': '21 - IPA',
        },
        {
            'name': '21B - Specialty IPA - Black IPA',
            'category': '21 - IPA',
        },
        {
            'name': '21B - Specialty IPA - Brown IPA',
            'category': '21 - IPA',
        },
        {
            'name': '21B - Specialty IPA - Red IPA',
            'category': '21 - IPA',
        },
        {
            'name': '21B - Specialty IPA - Rye IPA',
            'category': '21 - IPA',
        },
        {
            'name': '21B - Specialty IPA - White IPA',
            'category': '21 - IPA',
        },
        {
            'name': '22A - Double IPA',
            'category': '22 - Strong American Ale',
        },
        {
            'name': '22B - American Strong Ale',
            'category': '22 - Strong American Ale',
        },
        {
            'name': '22C - American Barleywine',
            'category': '22 - Strong American Ale',
        },
        {
            'name': '22D - Wheatwine',
            'category': '22 - Strong American Ale',
        },
        {
            'name': '23A - Berliner Weisse',
            'category': '23 - European Sour Ale',
        },
        {
            'name': '23B - Flanders Red Ale',
            'category': '23 - European Sour Ale',
        },
        {
            'name': '23C - Oud Bruin',
            'category': '23 - European Sour Ale',
        },
        {
            'name': '23D - Lambic',
            'category': '23 - European Sour Ale',
        },
        {
            'name': '23E - Gueuze ',
            'category': '23 - European Sour Ale',
        },
        {
            'name': '23F - Fruit Lambic',
            'category': '23 - European Sour Ale',
        },
        {
            'name': '24A - Witbier',
            'category': '24 - Belgian Ale',
        },
        {
            'name': '24B - Belgian Pale Ale',
            'category': '24 - Belgian Ale',
        },
        {
            'name': '24C - Bière de Garde',
            'category': '24 - Belgian Ale',
        },
        {
            'name': '25A - Belgian Blond Ale',
            'category': '25 - Strong Belgian Ale',
        },
        {
            'name': '25B - Saison',
            'category': '25 - Strong Belgian Ale',
        },
        {
            'name': '25C - Belgian Golden Strong Ale',
            'category': '25 - Strong Belgian Ale',
        },
        {
            'name': '26A - Trappist Single',
            'category': '26 - Trappist Ale',
        },
        {
            'name': '26B - Belgian Dubbel',
            'category': '26 - Trappist Ale',
        },
        {
            'name': '26C - Belgian Tripel',
            'category': '26 - Trappist Ale',
        },
        {
            'name': '26D - Belgian Dark Strong Ale',
            'category': '26 - Trappist Ale',
        },
        {
            'name': '27A - Gose',
            'category': '27 - Historical Beer',
        },
        {
            'name': '27A - Kentucky Common',
            'category': '27 - Historical Beer',
        },
        {
            'name': '27A - Lichtenhainer',
            'category': '27 - Historical Beer',
        },
        {
            'name': '27A - London Brown Ale',
            'category': '27 - Historical Beer',
        },
        {
            'name': '27A - Piwo Grodziskie',
            'category': '27 - Historical Beer',
        },
        {
            'name': '27A - Pre-Prohibition Lager',
            'category': '27 - Historical Beer',
        },
        {
            'name': '27A - Pre-Prohibition Porter',
            'category': '27 - Historical Beer',
        },
        {
            'name': '27A - Roggenbier',
            'category': '27 - Historical Beer',
        },
        {
            'name': '27A - Sahti',
            'category': '27 - Historical Beer',
        },
        {
            'name': '28A - Brett Beer',
            'category': '28 - American Wild Ale',
        },
        {
            'name': '28B - Mixed-Fermentation Sour Beer',
            'category': '28 - American Wild Ale',
        },
        {
            'name': '28C - Wild Specialty Beer',
            'category': '28 - American Wild Ale',
        },
        {
            'name': '29A - Fruit Beer',
            'category': '29 - Fruit Beer',
        },
        {
            'name': '29B - Fruit and Spice Beer',
            'category': '29 - Fruit Beer',
        },
        {
            'name': '29C - Specialty Fruit Beer',
            'category': '29 - Fruit Beer',
        },
        {
            'name': '30A - Spice, Herb or Vegetable Beer',
            'category': '30 - Spiced Beer',
        },
        {
            'name': '30B - Autumn Seasonal Beer',
            'category': '30 - Spiced Beer',
        },
        {
            'name': '30C - Winter Seasonal Beer',
            'category': '30 - Spiced Beer',
        },
        {
            'name': '31A - Alternative Grain Beer',
            'category': '31 - Alternative Fermentables Beer',
        },
        {
            'name': '31B - Alternative Sugar Beer',
            'category': '31 - Alternative Fermentables Beer',
        },
        {
            'name': '32A - Classic Style Smoked Beer',
            'category': '32 - Smoked Beer',
        },
        {
            'name': '32B - Specialty Smoked Beer',
            'category': '32 - Smoked Beer',
        },
        {
            'name': '33A - Wood-Aged Beer',
            'category': '33 - Wood Beer',
        },
        {
            'name': '33B - Specialty Wood-Aged Beer',
            'category': '33 - Wood Beer',
        },
        {
            'name': '34A - Clone Beer',
            'category': '34 - Specialty Beer',
        },
        {
            'name': '34B - Mixed-Style Beer',
            'category': '34 - Specialty Beer',
        },
        {
            'name': '34C - Experimental Beer',
            'category': '34 - Specialty Beer',
        },
    ]
    BJCPStyle = apps.get_model('competitions', 'BJCPstyle')
    BJCPCategory = apps.get_model('competitions', 'BJCPCategory')
    for d in style_data:
        category = BJCPCategory.objects.get(name=d['category'])
        cc = BJCPStyle(name=d['name'], category=category[0])
        cc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_populate_categories'),
    ]

    operations = [
        migrations.RunPython(populate_style),
    ]
