# Generated by Django 2.2.2 on 2019-07-06 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_auto_20190702_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='style',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='competitions.BJCPstyle'),
        ),
    ]
