# Generated by Django 2.2.2 on 2019-07-19 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0011_populate_styles'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of addition')),
                ('fullname', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('bjcp_license_no', models.CharField(blank=True, default='', max_length=15)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='competitions.Role')),
            ],
        ),
    ]
