# Generated by Django 2.2.2 on 2019-07-13 20:11

from django.db import migrations, models


def populate_role(apps, schema_editor):
    role_data = [
        {
            'name': 'Super User',
            'level': 0,
        },
        {
            'name': 'Organizer',
            'level': 1,
        },
        {
            'name': 'Judge',
            'level': 2,
        },
        {
            'name': 'Brewer',
            'level': 3,
        },
        {
            'name': 'Unprivileged User',
            'level': 100,
        },
    ]
    Roles = apps.get_model('competitions', 'Role')
    for r in role_data:
        cc = Roles(name=r['name'])
        cc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_populate_styles'),
    ]

    operations = [
        migrations.RunPython(populate_role),
    ]