# Generated by Django 2.2.2 on 2019-07-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_enduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='enduser',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
