# Generated by Django 2.2.2 on 2019-07-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_enduser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enduser',
            old_name='bjcp_license_no',
            new_name='bjcp_id',
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='date',
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='enabled',
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='enduser',
            name='role',
        ),
        migrations.AddField(
            model_name='enduser',
            name='elegibleforjudge',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
