# Generated by Django 2.2.2 on 2019-08-11 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_contestscoresheet_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestscoresheetdescriptor',
            unique_together={('score_sheet', 'descriptor')},
        ),
    ]
