# Generated by Django 2.2.2 on 2019-07-20 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('competitions', '0014_auto_20190720_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enduser',
            name='login',
        ),
        migrations.AddField(
            model_name='enduser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enduser',
            name='elegibleforjudge',
            field=models.BooleanField(default=False),
        ),
    ]
