# Generated by Django 2.2.2 on 2019-08-13 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_auto_20190811_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestcategory',
            name='style',
            field=models.ForeignKey(default=61, on_delete=django.db.models.deletion.DO_NOTHING, to='competitions.BJCPstyle'),
            preserve_default=False,
        ),
    ]
